=== wim-va/50kView/Gegevensverwerking en databanken/XML/XML-bestanden/items.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="categorie" type="xs:string" />
							<xs:element name="omschrijving" type="xs:string" />
							<xs:element name="prijs">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:decimal">
											<xs:attribute name="valuta" default="EUR">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="USD" />
														<xs:enumeration value="EUR" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wim-va/50kView/Gegevensverwerking en databanken/XML/XML-bestanden/itemsxsd.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!--Een XML bestand met CD- en boekdata -->
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="items.xsd">
	<item id="id1">
		<categorie>CD</categorie>
		<omschrijving>&apos;s Nachts kouder dan XML</omschrijving>
		<prijs>5.20</prijs> 
	</item>
	<item id="id2">
		<categorie>Boek</categorie>
		<omschrijving>XML Family of Specifications</omschrijving>
		<prijs valuta="USD">49.99</prijs>
	</item>
	<item id="id3">
		<categorie>CD</categorie>
		<omschrijving>Ethisch XML</omschrijving>
		<prijs>3.20</prijs>
	</item>
</items>
