=== wim-va/50kView/Gegevensverwerking en databanken/XML/XML-bestanden/oefSchema.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="cursisten">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="cursist" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="naam" type="xsd:string" />
					<xsd:element name="pc" type="xsd:string" />
				</xsd:sequence>
				<xsd:attribute name="id" type="xsd:ID" use="required" />
				</xsd:complexType>
	</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
</xsd:schema>

=== wim-va/50kView/Gegevensverwerking en databanken/XML/XML-bestanden/oefSchema.xml
<?xml version="1.0"?>
<cursisten xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="oefSchema.xsd" >
   <cursist id="k1">
      <naam>Joske</naam>
      <pc>pc101</pc>
   </cursist>
   <cursist id="k2">
      <naam>Lewieke</naam>
      <pc>pc101</pc>
   </cursist>
   <cursist id="k3">
      <naam>Jantje</naam>
      <pc>pc102</pc>
   </cursist>
</cursisten>
