=== wim-va/50kView/Gegevensverwerking en databanken/XML/XML-bestanden/validmemo2.dtd
<!ELEMENT memos (memo)*>
   <!ELEMENT memo (voor, van, datum, antwoord?, titel, tekst)>
   <!ATTLIST memo id ID #REQUIRED>
   <!ATTLIST memo xml:lang NMTOKEN #IMPLIED>
   <!ELEMENT voor (#PCDATA)>
   <!ELEMENT van (#PCDATA)>
   <!ELEMENT datum (dag, maand, jaar)>
   <!ATTLIST datum zone CDATA #REQUIRED>
   <!ELEMENT dag (#PCDATA)>
   <!ELEMENT maand (#PCDATA)>
   <!ELEMENT jaar (#PCDATA)>
   <!ELEMENT antwoord EMPTY>
   <!ATTLIST antwoord idref IDREF #REQUIRED>
   <!ELEMENT titel (#PCDATA)>
   <!ELEMENT tekst (#PCDATA)>

=== wim-va/50kView/Gegevensverwerking en databanken/XML/XML-bestanden/validmemo2.xml
<?xml version="1.0"?>
<!-- validmemo2.xml -->
<!-- Dit is commentaar -->
<!DOCTYPE memos SYSTEM "validmemo2.dtd">
<memos>
   <memo id="C1" xml:lang="nl-BE">
      <voor>
         Carlos
         <!--testje -->
      </voor>
      <van>Jef</van>
      <datum zone="EST">
         <dag>9</dag>
         <maand>5</maand>
         <jaar>2001</jaar>
      </datum>
      <titel>XML</titel>
      <tekst>Carlos, ik begin vandaag met de cursus XML</tekst>
   </memo>
   <memo id="C2" xml:lang="nl-BE">
      <voor>Jef</voor>
      <van>Carlos</van>
      <datum zone="EST">
         <dag>9</dag>
         <maand>5</maand>
         <jaar>2001</jaar>
      </datum>
      <antwoord idref="C1"/>
      <titel>Re:XML</titel>
      <tekst>Dat is heel goed. Ik verhoog meteen je loon.</tekst>
   </memo>
</memos>
